# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9f736b12cabd4961def562a6dce4f2e2110a8385195f40da3e6e994ddc47680b1f612256eb880283b8903d94070489c014f1eafaa91f80f920622ee7fe066ac

test:
  secret_key_base: 7a8a443d7bc2cf229cc6acbc62ed31b2ab5010a16470187bc350a218e59d4306fe9a95fbb63706f2ef817f995d3417e63ce47332455a498e061390bad9c3d916

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
