# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f759e17a49c44c209099814645d6599610dd0e69be0492bdff054584349ae760a24ce536127bc6f12ef1cf15433663b46c0004de3fe7e3188b6f0e410cef2f98

test:
  secret_key_base: e8dbed1ab21948e43679aebe2b56d99fd75c0348e2667ba98d1cbdde235b25c09555fa00c3974bc8c748a65dbf55ab574ee3686926ee84675903ca87b70ba24d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
